const fakeStatus = [
    {id:1, status: "Я люблю Реакт"},
    {id:2, status: "Я люблю Реакт"},
    {id:3, status: "Я люблю Реакт"},
    {id:4, status: "Я люблю Реакт"},
    {id:5, status: "Я люблю Реакт"},
    {id:1, status: "Я люблю Реакт"},
    {id:1, status: "Я люблю Реакт"},
    {id:1, status: "Я люблю Реакт"},
    {id:1, status: "Я люблю Реакт"},
    {id:1, status: "Я люблю Реакт"},
    {id:1, status: "Я люблю Реакт"},
    {id:1, status: "Я люблю Реакт"},
    {id:1, status: "Я люблю Реакт"},
    {id:1, status: "Я люблю Реакт"},
    {id:1, status: "Я люблю Реакт"},
    {id:1, status: "Я люблю Реакт"},
    {id:1, status: "Я люблю Реакт"},
    {id:1, status: "Я люблю Реакт"},
    {id:1, status: "Я люблю Реакт"},
    
];